# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(814, 677)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_word_file_path = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_word_file_path.setFont(font)
        self.lineEdit_word_file_path.setObjectName("lineEdit_word_file_path")
        self.verticalLayout_2.addWidget(self.lineEdit_word_file_path)
        self.openButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        self.openButton.setMinimumSize(QtCore.QSize(120, 30))
        self.openButton.setMaximumSize(QtCore.QSize(1800, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.openButton.setFont(font)
        self.openButton.setObjectName("openButton")
        self.verticalLayout_2.addWidget(self.openButton)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 3, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 3, 4)
        self.doubleSpinBox_y_max = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_y_max.setMinimumSize(QtCore.QSize(70, 0))
        self.doubleSpinBox_y_max.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_y_max.setFont(font)
        self.doubleSpinBox_y_max.setMinimum(-9999.0)
        self.doubleSpinBox_y_max.setObjectName("doubleSpinBox_y_max")
        self.gridLayout_2.addWidget(self.doubleSpinBox_y_max, 0, 0, 1, 1)
        self.doubleSpinBox_y_min = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_y_min.setMinimumSize(QtCore.QSize(70, 0))
        self.doubleSpinBox_y_min.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_y_min.setFont(font)
        self.doubleSpinBox_y_min.setMinimum(-9999.0)
        self.doubleSpinBox_y_min.setMaximum(9999.0)
        self.doubleSpinBox_y_min.setObjectName("doubleSpinBox_y_min")
        self.gridLayout_2.addWidget(self.doubleSpinBox_y_min, 2, 0, 1, 1)
        self.spinBox_x_max = QtWidgets.QSpinBox(self.tab)
        self.spinBox_x_max.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_x_max.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_x_max.setFont(font)
        self.spinBox_x_max.setMinimum(-9999)
        self.spinBox_x_max.setMaximum(9999)
        self.spinBox_x_max.setProperty("value", 400)
        self.spinBox_x_max.setObjectName("spinBox_x_max")
        self.gridLayout_2.addWidget(self.spinBox_x_max, 3, 4, 1, 1)
        self.spinBox_x_min = QtWidgets.QSpinBox(self.tab)
        self.spinBox_x_min.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_x_min.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_x_min.setFont(font)
        self.spinBox_x_min.setMinimum(-9999)
        self.spinBox_x_min.setMaximum(9999)
        self.spinBox_x_min.setProperty("value", 0)
        self.spinBox_x_min.setObjectName("spinBox_x_min")
        self.gridLayout_2.addWidget(self.spinBox_x_min, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit_word_file_path.setText(_translate("Dialog", ".\\test.docx"))
        self.openButton.setText(_translate("Dialog", "Сохранить в Word"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))

