# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 542)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_open_file2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_open_file2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/nenuzhny/Pictures/FileIcon20x20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_open_file2.setIcon(icon)
        self.pushButton_open_file2.setObjectName("pushButton_open_file2")
        self.gridLayout.addWidget(self.pushButton_open_file2, 2, 0, 1, 1)
        self.textEdit_fileName2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_fileName2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_fileName2.setObjectName("textEdit_fileName2")
        self.gridLayout.addWidget(self.textEdit_fileName2, 2, 1, 1, 6)
        self.textEdit_fileName1 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_fileName1.setMinimumSize(QtCore.QSize(500, 0))
        self.textEdit_fileName1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_fileName1.setObjectName("textEdit_fileName1")
        self.gridLayout.addWidget(self.textEdit_fileName1, 1, 1, 1, 6)
        self.checkBox_filePlot1 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_filePlot1.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot1.setText("")
        self.checkBox_filePlot1.setChecked(True)
        self.checkBox_filePlot1.setTristate(False)
        self.checkBox_filePlot1.setObjectName("checkBox_filePlot1")
        self.gridLayout.addWidget(self.checkBox_filePlot1, 1, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 7, 1, 1)
        self.pushButton_open_file1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_open_file1.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file1.setText("")
        self.pushButton_open_file1.setIcon(icon)
        self.pushButton_open_file1.setObjectName("pushButton_open_file1")
        self.gridLayout.addWidget(self.pushButton_open_file1, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.checkBox_filePlot2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_filePlot2.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot2.setText("")
        self.checkBox_filePlot2.setChecked(True)
        self.checkBox_filePlot2.setObjectName("checkBox_filePlot2")
        self.gridLayout.addWidget(self.checkBox_filePlot2, 2, 7, 1, 1)
        self.pushButton_open_file3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_open_file3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file3.setText("")
        self.pushButton_open_file3.setIcon(icon)
        self.pushButton_open_file3.setObjectName("pushButton_open_file3")
        self.gridLayout.addWidget(self.pushButton_open_file3, 3, 0, 1, 1)
        self.textEdit_fileName3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_fileName3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_fileName3.setObjectName("textEdit_fileName3")
        self.gridLayout.addWidget(self.textEdit_fileName3, 3, 1, 1, 6)
        self.checkBox_filePlot3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_filePlot3.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot3.setText("")
        self.checkBox_filePlot3.setChecked(True)
        self.checkBox_filePlot3.setObjectName("checkBox_filePlot3")
        self.gridLayout.addWidget(self.checkBox_filePlot3, 3, 7, 1, 1)
        self.pushButton_open_file4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_open_file4.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file4.setText("")
        self.pushButton_open_file4.setIcon(icon)
        self.pushButton_open_file4.setObjectName("pushButton_open_file4")
        self.gridLayout.addWidget(self.pushButton_open_file4, 4, 0, 1, 1)
        self.textEdit_fileName4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_fileName4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_fileName4.setObjectName("textEdit_fileName4")
        self.gridLayout.addWidget(self.textEdit_fileName4, 4, 1, 1, 6)
        self.checkBox_filePlot4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_filePlot4.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot4.setText("")
        self.checkBox_filePlot4.setChecked(True)
        self.checkBox_filePlot4.setObjectName("checkBox_filePlot4")
        self.gridLayout.addWidget(self.checkBox_filePlot4, 4, 7, 1, 1)
        self.pushButton_open_file5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_open_file5.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file5.setText("")
        self.pushButton_open_file5.setIcon(icon)
        self.pushButton_open_file5.setObjectName("pushButton_open_file5")
        self.gridLayout.addWidget(self.pushButton_open_file5, 5, 0, 1, 1)
        self.textEdit_fileName5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_fileName5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_fileName5.setObjectName("textEdit_fileName5")
        self.gridLayout.addWidget(self.textEdit_fileName5, 5, 1, 1, 6)
        self.checkBox_filePlot5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_filePlot5.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot5.setText("")
        self.checkBox_filePlot5.setChecked(True)
        self.checkBox_filePlot5.setObjectName("checkBox_filePlot5")
        self.gridLayout.addWidget(self.checkBox_filePlot5, 5, 7, 1, 1)
        self.pushButton_open_file6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_open_file6.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file6.setText("")
        self.pushButton_open_file6.setIcon(icon)
        self.pushButton_open_file6.setObjectName("pushButton_open_file6")
        self.gridLayout.addWidget(self.pushButton_open_file6, 6, 0, 1, 1)
        self.textEdit_fileName6 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_fileName6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_fileName6.setObjectName("textEdit_fileName6")
        self.gridLayout.addWidget(self.textEdit_fileName6, 6, 1, 1, 6)
        self.checkBox_filePlot6 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_filePlot6.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot6.setText("")
        self.checkBox_filePlot6.setChecked(True)
        self.checkBox_filePlot6.setObjectName("checkBox_filePlot6")
        self.gridLayout.addWidget(self.checkBox_filePlot6, 6, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_S11 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S11.setFont(font)
        self.pushButton_S11.setObjectName("pushButton_S11")
        self.horizontalLayout.addWidget(self.pushButton_S11)
        self.pushButton_S12 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S12.setFont(font)
        self.pushButton_S12.setObjectName("pushButton_S12")
        self.horizontalLayout.addWidget(self.pushButton_S12)
        self.pushButton_S21 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S21.setFont(font)
        self.pushButton_S21.setObjectName("pushButton_S21")
        self.horizontalLayout.addWidget(self.pushButton_S21)
        self.pushButton_S22 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S22.setFont(font)
        self.pushButton_S22.setObjectName("pushButton_S22")
        self.horizontalLayout.addWidget(self.pushButton_S22)
        self.pushButton_VSWR1 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VSWR1.setFont(font)
        self.pushButton_VSWR1.setObjectName("pushButton_VSWR1")
        self.horizontalLayout.addWidget(self.pushButton_VSWR1)
        self.pushButton_VSWR2 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VSWR2.setFont(font)
        self.pushButton_VSWR2.setObjectName("pushButton_VSWR2")
        self.horizontalLayout.addWidget(self.pushButton_VSWR2)
        self.pushButton_Rx1 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Rx1.setFont(font)
        self.pushButton_Rx1.setObjectName("pushButton_Rx1")
        self.horizontalLayout.addWidget(self.pushButton_Rx1)
        self.pushButton_Rx2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_Rx2.setObjectName("pushButton_Rx2")
        self.horizontalLayout.addWidget(self.pushButton_Rx2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Вывод"))
        self.label.setText(_translate("Dialog", "Откр."))
        self.label_2.setText(_translate("Dialog", "Расположение файла"))
        self.pushButton_S11.setText(_translate("Dialog", "S11"))
        self.pushButton_S12.setText(_translate("Dialog", "S12"))
        self.pushButton_S21.setText(_translate("Dialog", "S21"))
        self.pushButton_S22.setText(_translate("Dialog", "S22"))
        self.pushButton_VSWR1.setText(_translate("Dialog", "VSWR1"))
        self.pushButton_VSWR2.setText(_translate("Dialog", "VSWR2"))
        self.pushButton_Rx1.setText(_translate("Dialog", "Rx1"))
        self.pushButton_Rx2.setText(_translate("Dialog", "Rx2"))

