# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(712, 390)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setIndent(15)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label_5.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setIndent(5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setMinimumSize(QtCore.QSize(55, 0))
        self.label_14.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_color2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_color2.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_color2.setFont(font)
        self.pushButton_color2.setText("")
        self.pushButton_color2.setObjectName("pushButton_color2")
        self.gridLayout_2.addWidget(self.pushButton_color2, 1, 1, 1, 1)
        self.spinBox_thickness6 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_thickness6.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_thickness6.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_thickness6.setFont(font)
        self.spinBox_thickness6.setProperty("value", 2)
        self.spinBox_thickness6.setObjectName("spinBox_thickness6")
        self.gridLayout_2.addWidget(self.spinBox_thickness6, 5, 2, 1, 1)
        self.comboBox_linetype6 = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_linetype6.setFont(font)
        self.comboBox_linetype6.setObjectName("comboBox_linetype6")
        self.gridLayout_2.addWidget(self.comboBox_linetype6, 5, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setMinimumSize(QtCore.QSize(20, 0))
        self.label_8.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.pushButton_color1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_color1.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_color1.setFont(font)
        self.pushButton_color1.setText("")
        self.pushButton_color1.setObjectName("pushButton_color1")
        self.gridLayout_2.addWidget(self.pushButton_color1, 0, 1, 1, 1)
        self.spinBox_thickness1 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_thickness1.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_thickness1.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_thickness1.setFont(font)
        self.spinBox_thickness1.setProperty("value", 2)
        self.spinBox_thickness1.setObjectName("spinBox_thickness1")
        self.gridLayout_2.addWidget(self.spinBox_thickness1, 0, 2, 1, 1)
        self.comboBox_linetype1 = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_linetype1.setFont(font)
        self.comboBox_linetype1.setObjectName("comboBox_linetype1")
        self.gridLayout_2.addWidget(self.comboBox_linetype1, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setMinimumSize(QtCore.QSize(20, 0))
        self.label_9.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.spinBox_thickness2 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_thickness2.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_thickness2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_thickness2.setFont(font)
        self.spinBox_thickness2.setProperty("value", 2)
        self.spinBox_thickness2.setObjectName("spinBox_thickness2")
        self.gridLayout_2.addWidget(self.spinBox_thickness2, 1, 2, 1, 1)
        self.comboBox_linetype2 = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_linetype2.setFont(font)
        self.comboBox_linetype2.setObjectName("comboBox_linetype2")
        self.gridLayout_2.addWidget(self.comboBox_linetype2, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMinimumSize(QtCore.QSize(20, 0))
        self.label_10.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.pushButton_color3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_color3.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_color3.setFont(font)
        self.pushButton_color3.setText("")
        self.pushButton_color3.setObjectName("pushButton_color3")
        self.gridLayout_2.addWidget(self.pushButton_color3, 2, 1, 1, 1)
        self.spinBox_thickness3 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_thickness3.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_thickness3.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_thickness3.setFont(font)
        self.spinBox_thickness3.setProperty("value", 2)
        self.spinBox_thickness3.setObjectName("spinBox_thickness3")
        self.gridLayout_2.addWidget(self.spinBox_thickness3, 2, 2, 1, 1)
        self.comboBox_linetype3 = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_linetype3.setFont(font)
        self.comboBox_linetype3.setObjectName("comboBox_linetype3")
        self.gridLayout_2.addWidget(self.comboBox_linetype3, 2, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setMinimumSize(QtCore.QSize(20, 0))
        self.label_11.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.pushButton_color4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_color4.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_color4.setFont(font)
        self.pushButton_color4.setText("")
        self.pushButton_color4.setObjectName("pushButton_color4")
        self.gridLayout_2.addWidget(self.pushButton_color4, 3, 1, 1, 1)
        self.spinBox_thickness4 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_thickness4.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_thickness4.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_thickness4.setFont(font)
        self.spinBox_thickness4.setProperty("value", 2)
        self.spinBox_thickness4.setObjectName("spinBox_thickness4")
        self.gridLayout_2.addWidget(self.spinBox_thickness4, 3, 2, 1, 1)
        self.comboBox_linetype4 = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_linetype4.setFont(font)
        self.comboBox_linetype4.setObjectName("comboBox_linetype4")
        self.gridLayout_2.addWidget(self.comboBox_linetype4, 3, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setMinimumSize(QtCore.QSize(20, 0))
        self.label_12.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.pushButton_color5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_color5.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_color5.setFont(font)
        self.pushButton_color5.setText("")
        self.pushButton_color5.setObjectName("pushButton_color5")
        self.gridLayout_2.addWidget(self.pushButton_color5, 4, 1, 1, 1)
        self.spinBox_thickness5 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_thickness5.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_thickness5.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_thickness5.setFont(font)
        self.spinBox_thickness5.setProperty("value", 2)
        self.spinBox_thickness5.setObjectName("spinBox_thickness5")
        self.gridLayout_2.addWidget(self.spinBox_thickness5, 4, 2, 1, 1)
        self.comboBox_linetype5 = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_linetype5.setFont(font)
        self.comboBox_linetype5.setObjectName("comboBox_linetype5")
        self.gridLayout_2.addWidget(self.comboBox_linetype5, 4, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setMinimumSize(QtCore.QSize(20, 0))
        self.label_13.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.pushButton_color6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_color6.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_color6.setFont(font)
        self.pushButton_color6.setText("")
        self.pushButton_color6.setObjectName("pushButton_color6")
        self.gridLayout_2.addWidget(self.pushButton_color6, 5, 1, 1, 1)
        self.comboBox_marker1 = QtWidgets.QComboBox(self.tab)
        self.comboBox_marker1.setObjectName("comboBox_marker1")
        self.gridLayout_2.addWidget(self.comboBox_marker1, 0, 4, 1, 1)
        self.comboBox_marker2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_marker2.setObjectName("comboBox_marker2")
        self.gridLayout_2.addWidget(self.comboBox_marker2, 1, 4, 1, 1)
        self.comboBox_marker3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_marker3.setObjectName("comboBox_marker3")
        self.gridLayout_2.addWidget(self.comboBox_marker3, 2, 4, 1, 1)
        self.comboBox_marker4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_marker4.setObjectName("comboBox_marker4")
        self.gridLayout_2.addWidget(self.comboBox_marker4, 3, 4, 1, 1)
        self.comboBox_marker5 = QtWidgets.QComboBox(self.tab)
        self.comboBox_marker5.setObjectName("comboBox_marker5")
        self.gridLayout_2.addWidget(self.comboBox_marker5, 4, 4, 1, 1)
        self.comboBox_marker6 = QtWidgets.QComboBox(self.tab)
        self.comboBox_marker6.setObjectName("comboBox_marker6")
        self.gridLayout_2.addWidget(self.comboBox_marker6, 5, 4, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(294, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.spinBox_impedance = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_impedance.setFont(font)
        self.spinBox_impedance.setMaximum(999)
        self.spinBox_impedance.setObjectName("spinBox_impedance")
        self.gridLayout_3.addWidget(self.spinBox_impedance, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_open_file2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_open_file2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/nenuzhny/Pictures/FileIcon20x20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_open_file2.setIcon(icon)
        self.pushButton_open_file2.setObjectName("pushButton_open_file2")
        self.gridLayout.addWidget(self.pushButton_open_file2, 2, 0, 1, 1)
        self.checkBox_filePlot1 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_filePlot1.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot1.setText("")
        self.checkBox_filePlot1.setChecked(True)
        self.checkBox_filePlot1.setTristate(False)
        self.checkBox_filePlot1.setObjectName("checkBox_filePlot1")
        self.gridLayout.addWidget(self.checkBox_filePlot1, 1, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.pushButton_open_file1 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_open_file1.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file1.setText("")
        self.pushButton_open_file1.setIcon(icon)
        self.pushButton_open_file1.setObjectName("pushButton_open_file1")
        self.gridLayout.addWidget(self.pushButton_open_file1, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.checkBox_filePlot2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_filePlot2.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot2.setText("")
        self.checkBox_filePlot2.setChecked(True)
        self.checkBox_filePlot2.setObjectName("checkBox_filePlot2")
        self.gridLayout.addWidget(self.checkBox_filePlot2, 2, 5, 1, 1)
        self.pushButton_open_file3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_open_file3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file3.setText("")
        self.pushButton_open_file3.setIcon(icon)
        self.pushButton_open_file3.setObjectName("pushButton_open_file3")
        self.gridLayout.addWidget(self.pushButton_open_file3, 3, 0, 1, 1)
        self.checkBox_filePlot3 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_filePlot3.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot3.setText("")
        self.checkBox_filePlot3.setChecked(True)
        self.checkBox_filePlot3.setObjectName("checkBox_filePlot3")
        self.gridLayout.addWidget(self.checkBox_filePlot3, 3, 5, 1, 1)
        self.pushButton_open_file4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_open_file4.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file4.setText("")
        self.pushButton_open_file4.setIcon(icon)
        self.pushButton_open_file4.setObjectName("pushButton_open_file4")
        self.gridLayout.addWidget(self.pushButton_open_file4, 4, 0, 1, 1)
        self.checkBox_filePlot4 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_filePlot4.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot4.setText("")
        self.checkBox_filePlot4.setChecked(True)
        self.checkBox_filePlot4.setObjectName("checkBox_filePlot4")
        self.gridLayout.addWidget(self.checkBox_filePlot4, 4, 5, 1, 1)
        self.pushButton_open_file5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_open_file5.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file5.setText("")
        self.pushButton_open_file5.setIcon(icon)
        self.pushButton_open_file5.setObjectName("pushButton_open_file5")
        self.gridLayout.addWidget(self.pushButton_open_file5, 5, 0, 1, 1)
        self.checkBox_filePlot5 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_filePlot5.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot5.setText("")
        self.checkBox_filePlot5.setChecked(True)
        self.checkBox_filePlot5.setObjectName("checkBox_filePlot5")
        self.gridLayout.addWidget(self.checkBox_filePlot5, 5, 5, 1, 1)
        self.pushButton_open_file6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_open_file6.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_open_file6.setText("")
        self.pushButton_open_file6.setIcon(icon)
        self.pushButton_open_file6.setObjectName("pushButton_open_file6")
        self.gridLayout.addWidget(self.pushButton_open_file6, 6, 0, 1, 1)
        self.checkBox_filePlot6 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_filePlot6.setMaximumSize(QtCore.QSize(30, 30))
        self.checkBox_filePlot6.setText("")
        self.checkBox_filePlot6.setChecked(True)
        self.checkBox_filePlot6.setObjectName("checkBox_filePlot6")
        self.gridLayout.addWidget(self.checkBox_filePlot6, 6, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.lineEdit_filename1 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_filename1.setText("")
        self.lineEdit_filename1.setObjectName("lineEdit_filename1")
        self.gridLayout.addWidget(self.lineEdit_filename1, 1, 3, 1, 1)
        self.lineEdit_filename2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_filename2.setText("")
        self.lineEdit_filename2.setObjectName("lineEdit_filename2")
        self.gridLayout.addWidget(self.lineEdit_filename2, 2, 3, 1, 1)
        self.lineEdit_filename3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_filename3.setText("")
        self.lineEdit_filename3.setObjectName("lineEdit_filename3")
        self.gridLayout.addWidget(self.lineEdit_filename3, 3, 3, 1, 1)
        self.lineEdit_filename4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_filename4.setText("")
        self.lineEdit_filename4.setObjectName("lineEdit_filename4")
        self.gridLayout.addWidget(self.lineEdit_filename4, 4, 3, 1, 1)
        self.lineEdit_filename5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_filename5.setText("")
        self.lineEdit_filename5.setObjectName("lineEdit_filename5")
        self.gridLayout.addWidget(self.lineEdit_filename5, 5, 3, 1, 1)
        self.lineEdit_filename6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_filename6.setText("")
        self.lineEdit_filename6.setObjectName("lineEdit_filename6")
        self.gridLayout.addWidget(self.lineEdit_filename6, 6, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_S11 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S11.setFont(font)
        self.pushButton_S11.setObjectName("pushButton_S11")
        self.verticalLayout_5.addWidget(self.pushButton_S11)
        self.pushButton_S11_ang = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S11_ang.setFont(font)
        self.pushButton_S11_ang.setObjectName("pushButton_S11_ang")
        self.verticalLayout_5.addWidget(self.pushButton_S11_ang)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_S12 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S12.setFont(font)
        self.pushButton_S12.setObjectName("pushButton_S12")
        self.verticalLayout_6.addWidget(self.pushButton_S12)
        self.pushButton_S12_ang = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S12_ang.setFont(font)
        self.pushButton_S12_ang.setObjectName("pushButton_S12_ang")
        self.verticalLayout_6.addWidget(self.pushButton_S12_ang)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_S21 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S21.setFont(font)
        self.pushButton_S21.setObjectName("pushButton_S21")
        self.verticalLayout_7.addWidget(self.pushButton_S21)
        self.pushButton_S21_ang = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S21_ang.setFont(font)
        self.pushButton_S21_ang.setObjectName("pushButton_S21_ang")
        self.verticalLayout_7.addWidget(self.pushButton_S21_ang)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_S22 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S22.setFont(font)
        self.pushButton_S22.setObjectName("pushButton_S22")
        self.verticalLayout_8.addWidget(self.pushButton_S22)
        self.pushButton_S22_ang = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_S22_ang.setFont(font)
        self.pushButton_S22_ang.setObjectName("pushButton_S22_ang")
        self.verticalLayout_8.addWidget(self.pushButton_S22_ang)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.pushButton_VSWR1 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VSWR1.setFont(font)
        self.pushButton_VSWR1.setObjectName("pushButton_VSWR1")
        self.horizontalLayout.addWidget(self.pushButton_VSWR1)
        self.pushButton_VSWR2 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VSWR2.setFont(font)
        self.pushButton_VSWR2.setObjectName("pushButton_VSWR2")
        self.horizontalLayout.addWidget(self.pushButton_VSWR2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_Rx1_re = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Rx1_re.setFont(font)
        self.pushButton_Rx1_re.setObjectName("pushButton_Rx1_re")
        self.verticalLayout_2.addWidget(self.pushButton_Rx1_re)
        self.pushButton_Rx1_im = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Rx1_im.setFont(font)
        self.pushButton_Rx1_im.setObjectName("pushButton_Rx1_im")
        self.verticalLayout_2.addWidget(self.pushButton_Rx1_im)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_Rx2_re = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Rx2_re.setFont(font)
        self.pushButton_Rx2_re.setObjectName("pushButton_Rx2_re")
        self.verticalLayout_3.addWidget(self.pushButton_Rx2_re)
        self.pushButton_Rx2_im = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Rx2_im.setFont(font)
        self.pushButton_Rx2_im.setObjectName("pushButton_Rx2_im")
        self.verticalLayout_3.addWidget(self.pushButton_Rx2_im)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.checkBox_do_not_delete_current_plots = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_do_not_delete_current_plots.setObjectName("checkBox_do_not_delete_current_plots")
        self.verticalLayout_4.addWidget(self.checkBox_do_not_delete_current_plots)
        spacerItem2 = QtWidgets.QSpacerItem(20, 201, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Цвет"))
        self.label_5.setText(_translate("Dialog", "Толщина"))
        self.label_6.setText(_translate("Dialog", "Тип линии"))
        self.label_14.setText(_translate("Dialog", "Маркер"))
        self.label_8.setText(_translate("Dialog", "1"))
        self.label_9.setText(_translate("Dialog", "2"))
        self.label_10.setText(_translate("Dialog", "3"))
        self.label_11.setText(_translate("Dialog", "4"))
        self.label_12.setText(_translate("Dialog", "5"))
        self.label_13.setText(_translate("Dialog", "6"))
        self.label_7.setText(_translate("Dialog", "Сопротивление"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Настройки"))
        self.label_3.setText(_translate("Dialog", "Вывод"))
        self.label.setText(_translate("Dialog", "Откр."))
        self.label_2.setText(_translate("Dialog", "Расположение файла"))
        self.pushButton_S11.setText(_translate("Dialog", "S11"))
        self.pushButton_S11_ang.setText(_translate("Dialog", "Фаза"))
        self.pushButton_S12.setText(_translate("Dialog", "S12"))
        self.pushButton_S12_ang.setText(_translate("Dialog", "Фаза"))
        self.pushButton_S21.setText(_translate("Dialog", "S21"))
        self.pushButton_S21_ang.setText(_translate("Dialog", "Фаза"))
        self.pushButton_S22.setText(_translate("Dialog", "S22"))
        self.pushButton_S22_ang.setText(_translate("Dialog", "Фаза"))
        self.pushButton_VSWR1.setText(_translate("Dialog", "КСВН1"))
        self.pushButton_VSWR2.setText(_translate("Dialog", "КСВН2"))
        self.pushButton_Rx1_re.setText(_translate("Dialog", "Z1_re"))
        self.pushButton_Rx1_im.setText(_translate("Dialog", "Z1_im"))
        self.pushButton_Rx2_re.setText(_translate("Dialog", "Z2_re"))
        self.pushButton_Rx2_im.setText(_translate("Dialog", "Z2_im"))
        self.checkBox_do_not_delete_current_plots.setText(_translate("Dialog", "Не удалять графики"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Графики"))

